os: linux
language: java
install: skip
jdk: openjdk11

addons:
  sonarcloud:
    organization: $SONARQUBE_ORG
    token:
      secure: $SONARQUBE_TOKEN

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build
    - stage: check
      script:
        - ./gradlew sonarqube -Dsonar.login=$SONARQUBE_TOKEN
    - stage: plugin publish
      script:
        - echo "Deploying to plugin portal ..."
        - ./gradlew publishPlugins
      on:
        branch: master
        env: _JAVA_OPTIONS="-Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET"
