os: linux
language: java
install: skip
jdk: openjdk11

addons:
  sonarcloud:
    organization: $SONARQUBE_ORG
    token:
      secure: $SONARQUBE_TOKEN

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build
    - stage: plugin publish
      if: branch = master
      script:
        - echo "Deploying to plugin portal ..."
        - ./gradlew publishPlugins -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET

cache:
  directories:
    - $HOME/.gradle/wrapper/dists/
