os: linux
language: java
install: skip
jdk: openjdk11

addons:
  sonarcloud:
    organization: $SONARQUBE_ORG
    token:
      secure: $SONARQUBE_TOKEN

script:
  - ./gradlew build
  - ./gradlew sonarqube -Dsonar.login=$SONARQUBE_TOKEN

jobs:
  include:
    - stage: plugin publish
      script:
        - echo "Deploying to plugin portal ..."
        - ./gradlew publishPlugins
      on:
        branch: master
        env: JAVA_OPTIONS="-Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET"
