name: Build

on:
  push:
#    branches:
#      - develop
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Release plugin
        default: false

jobs:
  build-project:
    runs-on: ubuntu-latest
    environment: qt-plugin
    steps:
      - name: Select Java version
        run: |
          case "${{ github.ref }}" in
            "refs/heads/release/1.1.x")
              echo SELECTED_JAVA_VERSION=8 >> "${GITHUB_ENV}"
              ;;
            "refs/heads/release/1.2.x")
              echo SELECTED_JAVA_VERSION=11 >> "${GITHUB_ENV}"
              ;;
            "refs/heads/release/1.3.x")
              echo SELECTED_JAVA_VERSION=17 >> "${GITHUB_ENV}"
              ;;
            *)
              echo SELECTED_JAVA_VERSION=21 >> "${GITHUB_ENV}"
          esac

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.SELECTED_JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Publish plugin to portal
        if: ${{ github.event.inputs.release || false }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          ./gradlew publishPlugins \
            -Dgradle.publish.key=$GRADLE_PUBLISH_KEY \
            -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET
